title = "Kitchen Runbook"
baseURL = "https://recipes.notthe.cloud"
languageCode = "en-ie"
defaultcontentlanguage = "en"
paginate = 20.0
enableGitInfo = true
sectionPagesMenu = "main"

[params]
author = "Cian Butler"
description = "Random recipes i've collected and made"
keywords = "recipes"
dateFormat = "Jan 2, 2006"

[permalinks]
posts = "/:filename"

[menu]
  [[menu.main]]
    name = "Me"
    url = "https://cianbutler.ie"
    weight = 10

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/tags/"
    weight = 2

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "PRINT"]

[outputFormats]
[outputFormats.printFormat]
  name = "print"
  mediaType = "text/html"
  baseName = "print"
  isPlainText = false
  rel = "print"
  isHTML = true
  noUgly = true
  permalinkable = true
  path = "print"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
