title = "Kitchen Runbook"
baseURL = "https://recipes.notthe.cloud"
languageCode = "en-ie"
defaultcontentlanguage = "en"
paginate = 20.0
enableGitInfo = true
sectionPagesMenu = "main"

[params]
author = "Cian Butler"
description = "Random recipes i've collected and made"
keywords = "recipes"
dateFormat = "Jan 2, 2006"
codePenUser = "butlerx"
katex = true
hideHeaderLinks = false
search = true
showThemeSwitcher = true
moveFooterToHeader = false

[permalinks]
posts = "/:filename"

[menu]
  [[menu.main]]
    name = "Me"
    url = "https://cianbutler.ie"
    weight = 10

  [[menu.main]]
    name = "Home"
    pre = "fas fa-home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    pre = "fas fa-tags"
    url = "/tags/"
    weight = 2

[params.front]
defaultAuthor = "Cian Butler"


[params.logo]
fileName = "/images/logo.webp"
height = 50
width = 200

[params.favicon]
fileName = "/images/icon.png"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "PRINT"]

[outputFormats]
[outputFormats.printFormat]
  name = "print"
  mediaType = "text/html"
  baseName = "print"
  isPlainText = false
  rel = "print"
  isHTML = true
  noUgly = true
  permalinkable = true
  path = "print"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
