[build]
  publish = "public"
  command = "yarn build"
  functions = "lambda"

[build.environment]
  NODE_VERSION = "8"
  YARN_VERSION = "1.2.1"
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional --verbose"
